language: go

go:
  - 1.6
  - 1.8
  - 1.9
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v
  - go install
  - $HOME/gopath/bin/roveralls -ignore=fixtures,.git
  - $HOME/gopath/bin/goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
